word_bank = ['JET', 'ALIEN', 'BOMB', 'SNOWMAN', 'TEACHER', 'DWARF', 'TRIP', 'SATURN',
             'GRASS', 'BRUSH', 'DRESS', 'SPINE', 'TRACK', 'CLIFF', 'VET', 'STOCK', 'MOSCOW', 'KEY',
             'RULER', 'PUMPKIN', 'PLASTIC', 'CRANE', 'HOSPITAL', 'SPELL', 'LOCK', 'DEATH', 'PRESS',
             'TRACK', 'VAN', 'PALM', 'LAB', 'MODEL', 'POINT', 'COTTON', 'PLATE', 'WHIP', 'CASINO',
             'CAR', 'OLIVE', 'DUCK', 'DIAMOND', 'FIGHTER', 'NET', 'CROSS', 'CONTRACT', 'SHOP',
             'BOW', 'TOKYO', 'TUBE', 'FISH', 'LINE', 'OCTOPUS', 'WAVE', 'GRACE', 'RING', 'WHALE',
             'WAKE', 'MOON', 'SEAL', 'MARCH', 'NEEDLE', 'DEGREE', 'POLICE', 'LION', 'MUG', 'WEB',
             'GHOST', 'BOOT', 'CONCERT', 'FAN', 'PIN', 'STICK', 'CHEST', 'SOCK', 'AMAZON', 'ROBOT',
             'CHAIR', 'LAP', 'WITCH', 'IVORY', 'BERLIN', 'KING', 'PART', 'ROW', 'FIGURE', 'CHARGE',
             'ICE', 'PIPE', 'YARD', 'NUT', 'LUCK', 'EMBASSY', 'WATER', 'LIFE', 'KETCHUP', 'AMERICA',
             'FACE', 'PITCH', 'BUGLE', 'PISTOL', 'PARK', 'BEACH', 'TAG', 'NOVEL', 'HORN', 'IRON',
             'HONEY', 'DOCTOR', 'SPRING', 'BELT', 'JAM', 'MERCURY', 'TABLE', 'LEAD', 'FOOT',
             'BLOCK', 'STAR', 'BERMUDA', 'BRIDGE', 'DRILL', 'CARD', 'MATCH', 'BALL', 'COURT',
             'LIGHT', 'ORGAN', 'ROULETTE', 'TIE', 'WATCH', 'FRANCE', 'POOL', 'ARM', 'ROBIN',
             'DATE', 'CHANGE', 'EAGLE', 'TIME', 'BUG', 'STRING', 'BEIJING', 'UNICORN', 'GAS',
             'POISON', 'TORCH', 'CIRCLE', 'FLUTE', 'PYRAMID', 'GOLD', 'PORT', 'PIT', 'ROSE',
             'GENIUS', 'PRINCESS', 'MINT', 'NIGHT', 'RACKET', 'SPY', 'CAST', 'TOWER', 'STATE',
             'BED', 'CARROT', 'OPERA', 'TICK', 'DISEASE', 'FLY', 'AFRICA', 'SWING', 'LINK',
             'MAIL', 'CRASH', 'FORK', 'COOK', 'AZTEC', 'ANGEL', 'ORANGE', 'LAWYER', 'LOG',
             'RABBIT', 'POLE', 'ENGLAND', 'HAND', 'DANCE', 'TAIL', 'GERMANY', 'MAPLE', 'SPIDER',
             'OIL', 'TEMPLE', 'APPLE', 'ROOT', 'PENGUIN', 'FILE', 'PAN', 'PUPIL', 'BUFFALO',
             'SOLDIER', 'BARK', 'CHINA', 'SHOE', 'STAFF', 'SPIKE', 'SERVER', 'NAIL', 'SOUND',
             'WELL', 'TAP', 'CYCLE', 'BAR', 'BOND', 'PLOT', 'DECK', 'BERRY', 'THIEF', 'BOLT',
             'MOLE', 'MARBLE', 'SCIENTIST', 'SCHOOL', 'GIANT', 'PAPER', 'MOUTH', 'SQUARE',
             'CODE', 'SUB', 'BACK', 'TRAIN', 'INDIA', 'PLANE', 'COMPOUND', 'SPACE', 'BOX',
             'FAIR', 'ALPS', 'CLUB', 'HORSE', 'CENTER', 'WASHER', 'GREECE', 'KIWI', 'POUND',
             'FIELD', 'ROUND', 'ROME', 'SLUG', 'HOOK', 'MOUNT', 'SCREEN', 'WORM', 'SINK',
             'PIRATE', 'CHICK', 'GAME', 'MASS', 'DOG', 'CROWN', 'VACUUM', 'FILM', 'SHOT',
             'TOOTH', 'HOTEL', 'PANTS', 'QUEEN', 'SNOW', 'GLASS', 'NOTE', 'PASTER',
             'TURKEY', 'BILL', 'OLYMPUS', 'PIANO', 'BAT', 'ATLANTIS', 'BUTTON', 'CAT',
             'PLAY', 'WALL', 'CHECK', 'TRUNK', 'BEAR', 'GROUND', 'MISSLE', 'MINE', 'COLD',
             'DINOSAUR', 'NINJA', 'SPOT']
